#!/usr/bin/perl
# http://aghaffar.developer.ch/
use vars '%I';
use lib '..';
use Slash;
*I = getSlashConf();                                        

my $subject = $ARGV[0] || "$I{'sitename'}: $I{'slogan'}";
my $text = join "\n", <>;
my $emails = sqlSelectMany("realemail", "users", "realemail is not null and realemail!=''");  
while (($email) = $emails->fetchrow()) {
	sendEmail($email, $subject, $text);
}

__END__
Run
./sendAdminEmail
and type the message.

If you have the message pre-written in a text file, 
simply pipe the message to the script.
cat filename | ./sendAdminEmail "
