#!/usr/bin/perl
# http://aghaffar.developer.ch/

BEGIN {
	unless ($ARGV[0]) {
		print "USAGE: $0 username [Real Name]\n";
		exit;
	}
}

use vars '%I';
use lib '..';
use Slash;
*I = getSlashConf();                                        
my $data;

# set this to 0 if you dont want that an email is sent to the user
# announcing that he/she has been promoted to an author.
my $sendEmail = 1;
my $emailSubject = "$I{'sitename'} : Author Privileges notification.";
# set this to default seclev
$data->{'seclev'} = 500;


$data->{'aid'} = shift @ARGV;
$data->{'name'} = join " ", @ARGV;
$data->{'name'} ||= $data->{'aid'};


($data->{email}, $data->{url}, $data->{pwd}) =
	sqlSelect("realemail, homepage, passwd", "users", "nickname='$data->{aid}'");

sqlInsert("authors", $data);


my $emailText = qq|
Dear $data->{'name'},

Congratulations.
You have now author/admin privelages on
$I{'sitename'} $I{'rootdir'}

You can log in the admin console at
$I{'rootdir'}/admin.pl

Your username is $data->{'aid'}
and your passwd is the first 8 characters of your
regular $I{'sitename'} password.

You can post stories, accept/reject stories from 
other users, change the look & feel of the site
etc.

Have fun!

$I{'siteadmin_name'}

|;

sendEmail($data->{email}, $emailSubject, $emailText);
