#!/usr/local/bin/perl -w

use strict;
use vars qw(%savedBlocks);
use File::Spec::Functions;
use LWP::UserAgent;
use HTTP::Request;
use URI::Escape;
use XML::RSS;

use Slash;
use Slash::Utility;

my $virtual_user = $ARGV[0];
createEnvironment($virtual_user);
my $constants = getCurrentStatic();
my $slashdb = getCurrentDB();

myMotd();

sub myMotd {
    local $/ = "\n%%\n";
    local *F;
    open F, "< $constants->{datadir}/htdocs/quotes.txt" or die $!;
    my $t;
    rand($.) < 1 && ($t = $_) while <F>;

    if ($t) {
        $t =~ s/[\n%]+$//;
        $t =~ s/</&lt;/g;
        $t =~ s/>/&gt;/g;
        $t =~ s/&(?!(?:[a-zA-Z0-9]+|#\d+);)/&amp;/g;
        $t =~ s/\015?\012/<BR>\n/g;
        $t =~ s/  /&nbsp; /g;
        my $tpid = $slashdb->getTemplateByName("motd", "tpid");
	$slashdb->setTemplate($tpid, { template => $t });
        main::portaldLog("set motd");
    }
}
