</FONT></TD>
         </TR>
        </TABLE><TABLE cellpadding="0" cellspacing="0" border="0" width="99%"
                align="center"    bgcolor="#ffffff">
            <TR>
             <TD colspan="4" align="center"><IMG src="http://images.slashdot.org/greendot.gif"
                alt="" width="80%" height="1" hspace="10" vspace="30"></TD>
            </TR><TR>
             <TD align=center><FONT size="2" face="arial,helvetica">
  <FORM method=GET action="http://slashdot.org/search.pl">
         <INPUT type="text" name="query" value="" size="20">
        <INPUT type="submit" value="Search">
  </FORM>
  </FONT>
  </TD>
  <TD bgcolor="#ffffff" width="25">  &nbsp; </TD>
  <TD align="center">
    <FONT size="2" face="arial,helvetica"><I>Men are those creatures with two legs and eight hands.
		-- Jayne Mansfield</I></FONT>
    </FONT>
  </TD></TR>
  <TR><TD colspan="4" align="center">
  <FONT size="1" color="#006666" face="arial,helvetica">

 All trademarks and copyrights on this
  page are owned by their respective owners.  Comments
  are owned by the Poster.
  The Rest &copy; 1997-2003 <A href="http://www.osdn.com/">OSDN</A>.
</FONT></CENTER>
             </TD>
            </TR>
           </TABLE>
        <CENTER>
          <FONT size=2 color="#006666">

         [ <A href="http://slashdot.org/"><Font color="#ffffff">home</FONT></A> |
         <A href="http://slashdot.org/awards.shtml"><Font color="#ffffff">awards</FONT></A> |
         <A href="http://slashdot.org/supporters.shtml"><FONT color="#ffffff">supporters</FONT></A> |
         <A href="http://CmdrTaco.net"><FONT color="#ffffff">rob's homepage</FONT></A> |
         <A href="http://slashdot.org/submit.pl"><FONT color="#ffffff">contribute story</FONT></A> |
         <A href="http://slashdot.org/search.pl"><FONT color="#ffffff">older articles</FONT></A> |
         <A href="http://www.osdn.com/"><FONT color="#ffffff">OSDN</FONT></A> |
         <A href="http://slashdot.org/advertising.shtml"><FONT color="#ffffff">advertising</FONT></A> |
         <A href="http://slashdot.org/pollBooth.pl"><FONT color="#ffffff">past polls</FONT></A> |
         <A href="http://slashdot.org/about.shtml"><FONT color="#ffffff">about</FONT></A> |
         <A href="http://slashdot.org/faq.shtml"><FONT color="#ffffff">faq</FONT></A> ]
           </FONT>
          </CENTER>
</BODY>
</HTML>
