#!perl -w
# run this document through perl to check its syntax
# To make it into plaintext at the standard location:
#	perldoc -tF docs/README.pod > README
use Pod::Checker;
podchecker(\*DATA);
__END__

=head1 NAME

README - Rehash ("Revised and Enhanced Homebrewed Automatic Storytelling Homepage")

=head1 DESCRIPTION

Rehash is a fork of the last open-source release of Rehash, which was
the basis of basis of slashdot.org. Rehash is a partial rewrite of Rehash
to increase functionality, improve usabilitiy, and an incremental port
to modern versions of Apache, perl, and mod_perl. It is designed for high
relaibility and scalability, with intergrated support for MySQL cluster,
multi-frontend support, and a strong adherence to the MVC development
methodology, clearly abstracting user-facing code from backend management.

In addition, rehash is designed to be fast, flexible, and highly scalable
and should scale to almost any load put to it. Furthermore, with support
for AppArmor, parameter filtering, and query hardening, rehash is resistant
to both SQL exploitation, and server compromise through the frontend. As
always, efforts continue to improve this wherever possible. As for proof of
its robustness, rehash powers soylentnews.org, and its ancestor powered
slashdot.org (which is one heck of a torture test).

See F<INSTALL> for information about B<installing> Rehash, including hardware
and software requirements. Read that document carefully, and follow the
instructions as precisely as possible.

Also see F<INSTALL> for information on  B<upgrading> from previous versions of
Rehash, Rehash or slashcode.

As noted in the FAQ, please send any bug reports, and subscribe to
mailing lists, at Rehash's github page.

    https://github.com/soylentnews/rehash

=head1 DOCUMENTATION

The F<.pod> documentation included with Rehash can be read with the
C<perldoc> program, included with perl, or translated using one of
the many C<pod2*> translators.

=over 4

=item Template Toolkit (version 2)

For more information on how to write templates, see the Template
Toolkit site.

http://www.template-toolkit.org/


=item RSS

For more information on RSS 1.0, and the RSS Rehash module.

http://purl.org/rss/1.0/

http://purl.org/rss/1.0/modules/slash/


=item Installation

The details on how to install, and upgrade, Rehash.

F<INSTALL>


=item API

The details of the API available in Rehash.

	perldoc Slash
	perldoc Slash::Utility
	perldoc Slash::Display
	perldoc Slash::DB

The modules represent the bulk of the public API of Rehash.
The other Rehash modules have embedded POD to be read with perldoc, too.
Some of the documentation here is woefully incomplete.

	use Source 'Luke';


=item HOWTOs

There are currently the beginnings of HOWTO documents
for templates, plugins, and themes.

F<docs/HOWTO-Plugins.pod>

F<docs/HOWTO-Templates.pod>

F<docs/HOWTO-Themes.pod>

=item Other

The slashguide document (previously called getting_started) helps
you get your feet wet and gives vital information for how to run
a Rehash site.

F<docs/slashguide.pod>

=item Authors

The authors and contributors of Rehash.

F<AUTHORS>


=back


=head1 LINKS

=over 4

=item Rehash

Primary user of rehash, and home of its developers.

https://soylentnews.org

=item Slashdot

The site that started it all.

http://slashdot.org/


=item GitHub (rehash repo)

Home of the rehash git repo.

https://github.com/soylentnews/rehash

=back


=head1 COPYRIGHT AND LICENSE

The information below applies to everything in this distribution,
except where noted.

Copyright 2014-2015 by the Rehash Developers and the SoylentNews Team.

    https://soylentnews.org
    https://github.com/soylentnews/rehash

Copyright 1997-2005 by Open Source Technology Group.

	http://www.ostg.com/

Rehash is free software; you can redistribute it and/or
modify it under the terms of the GNU General Public License
as published by the Free Software Foundation; either version 2
of the License, or (at your option) any later version.

Rehash is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU General Public License for more details.

You should have received a copy of the GNU General Public License
along with Rehash (F<COPYING>); if not, go to http://www.fsf.org/
or write to the Free Software Foundation, Inc., 59 Temple Place -
Suite 330, Boston, MA 02111-1307, USA.



=head1 VERSION

$Id$
